// ======================================================================
// \title  SpiDriver.hpp
// \author [Your Name]
// \brief  hpp file for SpiDriver component implementation class for GR740 (RTEMS)
//
// \copyright
// Copyright 2025, [Your Organization or Name].
// ALL RIGHTS RESERVED.
//
// ======================================================================

#ifndef DRV_RTEMS_GR740_SPI_DRIVER_HPP
#define DRV_RTEMS_GR740_SPI_DRIVER_HPP

#include "Drv/RTEMS/GR740/SpiDriver/GR740SpiDriverComponentAc.hpp" // Generated by fprime-codegen
#include "Drv/RTEMS/include/DriverCommon.hpp"
#include <FpConfig.hpp>

namespace Drv {

class SpiDriver final : public GR740SpiDriverComponentBase {
  public:
    // SPI clock frequency type (in Hz)
    typedef U32 SpiFrequency;

    // SPI mode enumeration (CPOL/CPHA)
    enum SpiMode {
        SPI_MODE_CPOL_LOW_CPHA_LOW,   //!< Mode 0: CPOL=0, CPHA=0
        SPI_MODE_CPOL_LOW_CPHA_HIGH,  //!< Mode 1: CPOL=0, CPHA=1
        SPI_MODE_CPOL_HIGH_CPHA_LOW,  //!< Mode 2: CPOL=1, CPHA=0
        SPI_MODE_CPOL_HIGH_CPHA_HIGH  //!< Mode 3: CPOL=1, CPHA=1
    };

    // ----------------------------------------------------------------------
    // Construction, initialization, and destruction
    // ----------------------------------------------------------------------

    //! Construct object SpiDriver
    SpiDriver(const char* const compName);

    //! Initialize the SPI driver
    void init(const NATIVE_INT_TYPE instance);

    //! Open and configure the SPI hardware
    bool open(NATIVE_INT_TYPE select, SpiFrequency clock, SpiMode spiMode);

    //! Destroy object SpiDriver
    ~SpiDriver();

  PRIVATE:
    // ----------------------------------------------------------------------
    // Handler implementations for user-defined typed input ports
    // ----------------------------------------------------------------------

    //! Handler implementation for SpiReadWrite port (full-duplex transfer)
    void SpiReadWrite_handler(
        const NATIVE_INT_TYPE portNum, /*!< The port number */
        Fw::Buffer& writeBuffer,       /*!< Buffer containing data to write */
        Fw::Buffer& readBuffer         /*!< Buffer to store read data */
    );

    // ----------------------------------------------------------------------
    // Private helper functions
    // ----------------------------------------------------------------------

    //! Wait for SPI operation to complete
    bool waitForComplete();

    // ----------------------------------------------------------------------
    // Private member variables
    // ----------------------------------------------------------------------

    volatile U8* m_baseAddr; //!< Pointer to SPI register base address
    NATIVE_INT_TYPE m_select; //!< Slave select index
    bool m_isOpen;            //!< Tracks if the driver is open
    U64 m_bytes;              //!< Total bytes transferred (for telemetry)

    // GR740 SPICTRL register offsets (based on GRLIB SPICTRL documentation)
    enum SpiRegisters {
        SPI_CTRL  = 0x00 / 4, //!< Control register
        SPI_STAT  = 0x04 / 4, //!< Status register
        SPI_DATA  = 0x08 / 4, //!< Data register
        SPI_SSEL  = 0x0C / 4, //!< Slave select register
        SPI_PRESC = 0x10 / 4  //!< Prescaler register
    };

    // SPI control register bits
    enum SpiCtrlBits {
        CTRL_EN   = 1 << 0,  //!< Enable SPI core
        CTRL_TXEN = 1 << 1,  //!< Transmit enable
        CTRL_RXEN = 1 << 2,  //!< Receive enable
        CTRL_MSTR = 1 << 3,  //!< Master mode
        CTRL_CPHA = 1 << 4,  //!< Clock phase (0 or 1)
        CTRL_CPOL = 1 << 5   //!< Clock polarity (0 or 1)
    };

    // SPI status register bits
    enum SpiStatBits {
        STAT_BUSY = 1 << 0, //!< Transfer in progress
        STAT_DONE = 1 << 1, //!< Transfer complete
        STAT_ERR  = 1 << 2  //!< Error condition
    };
};

} // end namespace Drv

#endif // DRV_RTEMS_GR740_SPI_DRIVER_HPP