#ifndef RTEMS_CONFIG_H
    #define RTEMS_CONFIG_H


#define LEON3  // Needed for some GRLIB configurations

#define RTEMS_DRVMGR_STARTUP 1
// #define HAS_L4STAT_DRIVER 1
// #define DEBUG_L4STAT 1
// #define USE_L4STAT 1
#define RTEMS_SMP 1
#define RTEMS_SMP_MAXIMUM_PROCESSORS 4
#define CONFIGURE_MICROSECONDS_PER_TICK 1000


#define CONFIGURE_EXECUTIVE_RAM_SIZE	(200*1024*1024) // 200 MB
#define CONFIGURE_INIT_TASK_STACK_SIZE (4*1024 * 1024) // 4MB

#define CONFIGURE_MALLOC_STATISTICS
#define CONFIGURE_NETWORK_MBUF_BYTES (512*1024)        // 512k for mbufs
#define CONFIGURE_NETWORK_MBUF_CLUSTER_BYTES (1024*1024)  // 1MB for mbuf clusters


// System resources
#define CONFIGURE_MAXIMUM_TASKS 100
#define CONFIGURE_MAXIMUM_SEMAPHORES 100
#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES 200
#define CONFIGURE_MAXIMUM_FILE_DESCRIPTORS 32
#define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS 32

// Init task table required
 #define CONFIGURE_RTEMS_INIT_TASKS_TABLE
extern int fprime_main(int argc, char* argv[]); // Declare the LedBlinker entry point
#define CONFIGURE_INIT_TASK_PRIORITY 50
#define CONFIGURE_INIT_TASK_INITIAL_MODES (RTEMS_PREEMPT | RTEMS_TIMESLICE)
#define CONFIGURE_INIT_TASK_ATTRIBUTES RTEMS_FLOATING_POINT
#define CONFIGURE_INIT_TASK_ENTRY_POINT   fprime_main  // F Prime’s entry point
#define CONFIGURE_INIT_TASK_NAME          rtems_build_name('F', 'P', 'R', 'M')


// Required for networking
#define CONFIGURE_MAXIMUM_DRIVERS 32

#define CONFIGURE_DRIVER_AMBAPP_GAISLER_GRETH
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_GRPCI2

#define CONFIGURE_MAXIMUM_NETWORK_INTERFACES 2

// Network task configuration
#define CONFIGURE_NETWORK_TASK_PRIORITY 64


#define CONFIGURE_DRIVER_AMBAPP_GAISLER_GRGPIO 


// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_GRSPW
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_GRCAN
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_OCCAN
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_B1553BRM
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_APBUART
// #define CONFIGURE_DRIVER_AMBAPP_MCTRL
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_PCIF
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_GRPCI
// #define CONFIGURE_DRIVER_PCI_GR_RASTA_IO
// #define CONFIGURE_DRIVER_PCI_GR_RASTA_TMTC
// #define CONFIGURE_DRIVER_PCI_GR_701

// IMPORTANT:: SMP OR AMP? THESE DEFINITIONS DEPEND TOTALLY ON THE STRATEGY
#define CONFIGURE_SMP_APPLICATION
#define CONFIGURE_SMP_MAXIMUM_PROCESSORS 4
#define CONFIGURE_MAXIMUM_PROCESSORS 4


// Define scheduler assignments for all 4 CPUs
// This makes all CPUs available for the scheduler
#define CONFIGURE_SCHEDULER_ASSIGNMENTS \
    RTEMS_SCHEDULER_ASSIGN(0, RTEMS_SCHEDULER_ASSIGN_PROCESSOR_MANDATORY), \
    RTEMS_SCHEDULER_ASSIGN(0, RTEMS_SCHEDULER_ASSIGN_PROCESSOR_MANDATORY), \
    RTEMS_SCHEDULER_ASSIGN(0, RTEMS_SCHEDULER_ASSIGN_PROCESSOR_MANDATORY), \
    RTEMS_SCHEDULER_ASSIGN(0, RTEMS_SCHEDULER_ASSIGN_PROCESSOR_MANDATORY)


#define CONFIGURE_MAXIMUM_POSIX_THREADS 32
#define CONFIGURE_MAXIMUM_POSIX_QUEUES 62
#define CONFIGURE_MAXIMUM_POSIX_MESSAGE_QUEUES 62
#define CONFIGURE_MAXIMUM_POSIX_CONDITION_VARIABLES 32
#define CONFIGURE_MAXIMUM_POSIX_SEMAPHORES 32
#define CONFIGURE_MAXIMUM_POSIX_MUTEXES 32



// Required drivers
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
// One of the following three must be defined
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
// #define CONFIGURE_APPLICATION_DOES_NOT_NEED_CLOCK_DRIVER
// #define CONFIGURE_APPLICATION_NEEDS_TIMER_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_MEMORY
#define CONFIGURE_APPLICATION_NEEDS_LIBC


#define CONFIGURE_DRIVER_AMBAPP_GAISLER_GPTIMER
#define CONFIGURE_DRIVER_AMBAPP_GAISLER_APBUART

#define CONFIGURE_APPLICATION_NEEDS_CPU_USAGE_STATISTICS
// #define CONFIGURE_DRIVER_AMBAPP_GAISLER_L4STAT




// #define CONFIGURE_INIT_TASK_ATTRIBUTES RTEMS_FLOATING_POINT
// #define CONFIGURE_SCHEDULER_ASSIGNMENTS
// #define RTEMS_SCHEDULER_ASSIGN index attr
// #define  RTEMS_SCHEDULER_ASSIGN_NO_SCHEDULER
/*
#define CONFIGURE_MAXIMUM_PROCESSORS 4
/* RTEMS SMP on CPU[1,2]. Something else on CPU[0,3]:
#define CONFIGURE_SCHEDULER_ASSIGNMENTS \
RTEMS_SCHEDULER_ASSIGN_NO_SCHEDULER, \
RTEMS_SCHEDULER_ASSIGN(0, RTEMS_SCHEDULER_ASSIGN_PROCESSOR_MANDATORY), \
RTEMS_SCHEDULER_ASSIGN(0, RTEMS_SCHEDULER_ASSIGN_PROCESSOR_MANDATORY), \
RTEMS_SCHEDULER_ASSIGN_NO_SCHEDULER
*/

/*
from the rcc-1.3.2 file:
Hardware  Define to include the deriver
GPTIMER AMBAPP_GAISLER_GPTIMER
APBUART AMBAPP_GAISLER_APBUART
GRETH AMBAPP_GAISLER_GRETH
GRSPW AMBAPP_GAISLER_GRSPW
GRCAN AMBAPP_GAISLER_GRCAN
OCCAN AMBAPP_GAISLER_OCCAN
GR1553B AMBAPP_GAISLER_GR1553B
GR1553B RT AMBAPP_GAISLER_GR1553BRT
GR1553B BM AMBAPP_GAISLER_GR1553BBM
GR1553B BC AMBAPP_GAISLER_GR1553BBC
B1553BRM AMBAPP_GAISLER_B1553BRM
B1553RT AMBAPP_GAISLER_B1553RT
GRTM AMBAPP_GAISLER_GRTM
GRTC AMBAPP_GAISLER_GRTC
PCIF PCI Host AMBAPP_GAISLER_PCIF
GRPCI PCI Host AMBAPP_GAISLER_GRPCI
GRPCI2 PCI Host AMBAPP_GAISLER_GRPCI2
FTMCTRL and MCTRL AMBAPP_MCTRL
SPICTRL AMBAPP_GAISLER_SPICTRL
I2CMST AMBAPP_GAISLER_I2CMST
GRGPIO AMBAPP_GAISLER_GRGPIO
GRPWM AMBAPP_GAISLER_GRPWM
GRADCDAC AMBAPP_GAISLER_GRADCDAC
SPWCUC AMBAPP_GAISLER_SPWCUC
GRCTM AMBAPP_GAISLER_GRCTM
SPW_ROUTER AMBAPP_GAISLER_SPW_ROUTER
AHBSTAT AMBAPP_GAISLER_AHBSTAT
GRAES AMBAPP_GAISLER_GRAES
GRPWRX AMBAPP_GAISLER_GRPWRX
L2CACHE AMBAPP_GAISLER_L2CACHE
GRIOMMU AMBAPP_GAISLER_GRIOMMU
AT697 PCI Host LEON2_AT697PCI
GRLIB-LEON2 AMBA PnP LEON2_AMBAPP
GR-RASTA-ADCDAC PCI_GR_RASTA_ADCDAC
GR-RASTA-IO PCI peripheral PCI_GR_RASTA_IO
GR-RASTA-TMTC PCI peripheral PCI_GR_RASTA_TMTC
GR-701 PCI peripheral PCI_GR_701
GR-TMTC-1553 PCI peripheral PCI_GR_TMTC_1553
GR-RASTA-SPW-ROUTER PCI peripheral PCI_GR_RASTA_SPW_ROUTER
GR-LEON4-N2X PCI peripheral PCI_GR_LEON4_N2X
GR-CPCI-GR740 PCI peripheral PCI_GR_CPCI_GR740
*/

// Uncommet the following line to avoid watchdog timeout
// #define RTEMS_NO_TIMEOUT  ((rtems_interval) WATCHDOG_NO_TIMEOUT)


// Use unlimited objects where possible
#define CONFIGURE_UNLIMITED_OBJECTS
#define CONFIGURE_UNIFIED_WORK_AREAS

// Include IMFS filesystem
#define CONFIGURE_FILESYSTEM_IMFS

// Define struct bintime if missing (add this part)
#include <stdint.h>
#include <time.h>
#ifndef _STRUCT_BINTIME
#define _STRUCT_BINTIME
struct bintime {
    time_t sec;    /* Seconds */
    uint64_t frac; /* Fractional part in 2^-64 seconds */
};
#endif





#define ENABLE_NETWORK


// Initialization
#define CONFIGURE_INIT



#endif  // RTEMS_CONFIG_H