// ======================================================================
// \title  I2cDriver.hpp
// \author [Your Name]
// \brief  hpp file for I2cDriver component implementation class for GR740 (RTEMS)
//
// \copyright
// Copyright 2025, [Your Organization or Name].
// ALL RIGHTS RESERVED.
//
// ======================================================================

#ifndef DRV_RTEMS_GR740_I2C_DRIVER_HPP
#define DRV_RTEMS_GR740_I2C_DRIVER_HPP

#include "Drv/RTEMS/GR740/I2cDriver/GR740I2cDriverComponentAc.hpp" // Generated by fprime-codegen
#include "Drv/RTEMS/include/DriverCommon.hpp"

namespace Drv {

class I2cDriver final : public GR740I2cDriverComponentBase {
  public:
    // ----------------------------------------------------------------------
    // Construction, initialization, and destruction
    // ----------------------------------------------------------------------

    //! Construct object I2cDriver
    I2cDriver(const char* const compName);

    //! Initialize the I2C driver with the device base address
    void init(const NATIVE_INT_TYPE instance);

    //! Open the I2C hardware
    bool open();

    //! Destroy object I2cDriver
    ~I2cDriver();

  PRIVATE:
    // ----------------------------------------------------------------------
    // Handler implementations for user-defined guarded input ports
    // ----------------------------------------------------------------------

    //! Handler implementation for write port
    Drv::I2cStatus write_handler(
        const NATIVE_INT_TYPE portNum, /*!< The port number */
        U32 addr,                      /*!< I2C device address */
        Fw::Buffer& serBuffer          /*!< Buffer containing data to write */
    );

    //! Handler implementation for read port
    Drv::I2cStatus read_handler(
        const NATIVE_INT_TYPE portNum, /*!< The port number */
        U32 addr,                      /*!< I2C device address */
        Fw::Buffer& serBuffer          /*!< Buffer to store read data */
    );

    //! Handler implementation for writeRead port
    Drv::I2cStatus writeRead_handler(
        const NATIVE_INT_TYPE portNum, /*!< The port number */
        U32 addr,                      /*!< I2C device address */
        Fw::Buffer& writeBuffer,       /*!< Buffer containing data to write */
        Fw::Buffer& readBuffer         /*!< Buffer to store read data */
    );

    // ----------------------------------------------------------------------
    // Private helper functions
    // ----------------------------------------------------------------------

    //! Wait for I2C operation to complete
    bool waitForComplete();

    // ----------------------------------------------------------------------
    // Private member variables
    // ----------------------------------------------------------------------

    volatile U32* m_baseAddr; //!< Pointer to I2C register base address
    bool m_isOpen;            //!< Tracks if the driver is open

    // GR740 I2C register offsets (based on GRLIB I2CMST documentation)
    enum I2cRegisters {
        I2C_CTRL = 0x00 / 4, //!< Control register
        I2C_STAT = 0x04 / 4, //!< Status register
        I2C_DATA = 0x08 / 4, //!< Data register
        I2C_ADDR = 0x0C / 4, //!< Address register
        I2C_PRES = 0x10 / 4  //!< Prescaler register
    };

    // I2C control register bits
    enum I2cCtrlBits {
        CTRL_EN   = 1 << 0, //!< Enable I2C core
        CTRL_STA  = 1 << 1, //!< Generate start condition
        CTRL_STO  = 1 << 2, //!< Generate stop condition
        CTRL_WR   = 1 << 3, //!< Write operation
        CTRL_RD   = 1 << 4, //!< Read operation
        CTRL_RSTA = 1 << 5  //!< Repeated start condition
    };

    // I2C status register bits
    enum I2cStatBits {
        STAT_BUSY = 1 << 0, //!< Bus busy
        STAT_DONE = 1 << 1, //!< Transfer complete
        STAT_ERR  = 1 << 2  //!< Error condition
    };
};

} // end namespace Drv

#endif // DRV_RTEMS_GR740_I2C_DRIVER_HPP